# Generated by Django 4.2.1 on 2023-06-05 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='coin',
            field=models.CharField(max_length=10),
        ),
    ]
